create table if not exists public.fuel_prices (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null,
    city text,
    station text,
    fuel text,
    price numeric,
    region text,
    location text
);

create unique index if not exists fuel_prices_observation_unique
on public.fuel_prices (
    created_at,
    coalesce(city, ''),
    coalesce(station, ''),
    coalesce(fuel, ''),
    price,
    coalesce(region, ''),
    coalesce(location, '')
);

create index if not exists fuel_prices_city_fuel_idx
on public.fuel_prices (city, fuel);

create index if not exists fuel_prices_created_at_idx
on public.fuel_prices (created_at desc);
